### ISSUE TITLE
fehmpytests  fails for transport3D

### ISSUE THREAD

**Issue by millerta** [lanl/FEHM#69]
fehmpytests  fails for transport3D (under construction).

3d_trac_rlp.trc 6 columns of data, the file in compare has 3.
The version in VV has a complicated set of perl drivers, so I suspect the input files need to be adjusted for this test.

Also, the python scripts do not fail gracefully:

```
es19:% python fehmpytests.py /project/eesdev/FEHM/FEHM_FORK/FEHM_gaz-linux/src_release/xfehm transport3d
transport3d (__main__.fehmTest.transport3d)
**Test transport3d** ... Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
ERROR

======================================================================
ERROR: transport3d (__main__.fehmTest.transport3d)
**Test transport3d**
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/eesdev/FEHM/FEHM-fehmpy/fehmpytests/fpost.py", line 1634, in fdiff
    if np.allclose(data1_flat, data2_flat, rtol=rtol, atol=atol, equal_nan=True):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in allclose
  File "/n/modules/Ubuntu-20.04-x86_64/anaconda-python/2023.09-0/lib/python3.11/site-packages/numpy/core/numeric.py", line 2270, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in isclose
  File "/n/modules/Ubuntu-20.04-x86_64/anaconda-python/2023.09-0/lib/python3.11/site-packages/numpy/core/numeric.py", line 2380, in isclose
    return within_tol(x, y, atol, rtol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/modules/Ubuntu-20.04-x86_64/anaconda-python/2023.09-0/lib/python3.11/site-packages/numpy/core/numeric.py", line 2361, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
                          ~^~
ValueError: operands could not be broadcast together with shapes (18120,) (22630,)

----------------------------------------------------------------------
Ran 1 test in 95.106s

FAILED (errors=1)
```

**Comment by millerta** [comment]
/project/eesdev/FEHM/VV_TESTS/VERIFICATION_V3.3.0lnx/transport3D
very different from VERIFICATION_V3.4win_64bit_runs_050724/transport3d

Copying the directory to lnx VV does not work, perl scripts fail.
Will need to construct fehmpytests using gaz windows that can run either win or linux

**Comment by millerta** [comment]
Some good new but not a fix yet for transport3d on fehmpytests

I was able to create linux output files with the VV test suite.
I copied those to a new compare directory and now the test does not fail.

So the code is fine (except for the format issue).
We can make a note in pending that code has correct results but test is pending inclusion until format is changed - or the python script is changed to read double lines or single lines.

I used my clone from master and copied VVlnx files into compare:

```
cp /project/eesdev/FEHM/VV_TESTS/VERIFICATION_V3.3.0lnx/transport3D/output_v3.6/*trc

/project/eesdev/FEHM/FEHM/fehmpytests

es19:% python fehmpytests.py /project/eesdev/FEHM/FEHM_FORK/FEHM_gaz-linux/src_release/xfehm transport3d
transport3d (__main__.fehmTest.transport3d)
**Test transport3d** ... Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
ok

----------------------------------------------------------------------
Ran 1 test in 280.871s

OK
es19:% ls transport3d/*
transport3d/3d_trac_rlpm_output:
3d_trac_rlpm.his  3d_trac_rlpm.out  3d_trac_rlpm.trc  none  nop.temp

transport3d/3d_trac_rlp_output:
3d_trac_rlp.his  3d_trac_rlp.out  3d_trac_rlp.trc  none  nop.temp

transport3d/3d_trxn_rlp_output:
3d_trxn_rlp.his  3d_trxn_rlp.out  3d_trxn_rlp.trc  none  nop.temp

transport3d/compare:
3d_trac_rlpm.trc  3d_trac_rlp.trc  3d_trxn_rlp.trc  readme

transport3d/compare_win:
3d_trac_rlpm.trc  3d_trac_rlp.trc  3d_trxn_rlp.trc  hide
```

**Comment by millerta** [comment]
Need development in fehmpytests.py to use the appropriate WIN or Linux .trc files for compare.

Partial fix for success on linux and windows, this works manually.
copy appropriate .trc files into compare or adjust fehmpytests to use the appropriate directory
compare_lnx for linux runs
compare_win for windows runs

**Comment by millerta** [comment]
Attached is a description of VV tests on windows and linux and how the output are checked.
The compare routine uses settings defined in the comparein file.
This will also provide the scale values to use as tolerance values in fehmpytests.

[vv_compare_transport3d.txt](https://github.com/user-attachments/files/17137517/vv_compare_transport3d.txt)

**Comment by millerta** [comment]
fehmpytests allows single or double line output, only the values are compared.
We will close this for now unless it is decided to pick one or the other for consistency across platforms.
