### ISSUE TITLE
fehmpytests fails for doe

### ISSUE THREAD

**Issue by millerta** [lanl/FEHM#76]
Compare with VV output files and check python scripts to determine why this test fails.

**Comment by millerta** [comment]
There are 3 sub tests; rlp, rlpm, and table. Only rlp is running.
doe_rlp.00003_sca_node.avs ../compare/doe_rlp.00003_sca_node.avs compares within precision.
WIN output matches VV, linux output matches lnx VV.

fehmpytests script fails with error:
```
python fehmpytests.py /project/eesdev/FEHM/FEHM_FORK/FEHM_gaz-linux/src_release/xfehm doe
doe (__main__.fehmTest.doe)
**Test the DOE Code Comparison Project, Problem 5, Case A** ... ERROR

======================================================================
ERROR: doe (__main__.fehmTest.doe)
**Test the DOE Code Comparison Project, Problem 5, Case A**
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/eesdev/FEHM/FEHM/fehmpytests/fpost.py", line 1009, in __init__
    if filename: self._filename=filename; self.read(filename)
                                          ^^^^^^^^^^^^^^^^^^^
  File "/project/eesdev/FEHM/FEHM/fehmpytests/fpost.py", line 1110, in read
    self._read_data_default(fname.split('_')[1].split('.')[0])
  File "/project/eesdev/FEHM/FEHM/fehmpytests/fpost.py", line 1159, in _read_data_default
    self._variables.append(hist_var_names[var_key])
                           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'rlp'

----------------------------------------------------------------------
Ran 1 test in 0.866s

FAILED (errors=1)
```
